lorom

incsrc "Backflip/Backflip.asm"
incsrc "Blackout Speedups/Door Transition Speed.asm"
incsrc "Bugfixes/MissileStationEnhancer.asm"
incsrc "Bugfixes/PBRevealTiles.asm"
incsrc "Bugfixes/ReserveTank_Bugfixes_by_Nodever2.asm"
incsrc "Bugfixes/ScrewAttackFrozenEnemis.asm"
incsrc "Bugfixes/vanillabugfixes.asm"
incsrc "ControlFreakProjectBase/1-ControlFreak2-PB0.7.3.asm"
incsrc "ControlFreakProjectBase/2-ControlFreak2-PB0.7.3-UIUpdate.asm"
incsrc "ControlFreakProjectBase/3-projectcontrolfreakbase-PB0.7.3.asm"
incsrc "DCMapPatch/DCMapPatch.asm"
incsrc "Ending Suit Palette/Ending Suit Palette.asm"
incsrc "Ending Time/XxYyZz END TIME.asm"
incsrc "Ending Totals/endingtotals.asm"
incsrc "Equipment Percentage Display/Equipment-Percentage-Display.asm"
incsrc "Equipment Screen Timer/Equipment-Screen-Timer.asm"
incsrc "Hard Mode Compatibility Hack/no.asm"
incsrc "Hard Mode Compatibility Hack/spikes.asm"
incsrc "Instant Bomb Explosion/Instant Bomb Explosion.asm"
incsrc "IntroSkip/IntroSkip.asm"
incsrc "ItemCircles/newitemcircles.asm"
incsrc "ItemSounds/itemsounds.asm"
incsrc "KraidFixes/kraid-pause-fix.asm"
incsrc "KraidFixes/postkraid-graphic-fix.asm"
incsrc "Menu Colored Samus/Menu Colored Samus.asm"
incsrc "Morph Roll Animation/MorphRoll.asm"
incsrc "MSU-1/MSU1.asm"
incsrc "Save Load Map/Save Load Map.asm"
incsrc "SaveLoad/saveload.asm"
incsrc "Skip Bomb Jump/Skip Bomb Jump.asm"
incsrc "Smooth Landing/Smooth Landing.asm"
incsrc "Spark Restart/Spark Restart.asm"
incsrc "Super Missile Fix/Super Missile Fix.asm"
incsrc "Super Missile Recoil/Super Missile Recoil.asm"
incsrc "TourianEvent/CutscenePLM.asm"
incsrc "Tractor Beam/TractorBeam.asm"
incsrc "misc.asm"